name: Update Repository

on:
  workflow_dispatch:
  repository_dispatch:
    types: [kick]

jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        run: |
          ./gen.sh
      - name: Add HTML Update
        run: |
          git add index.html
          git commit -m "Regenerated HTML"
          git push
      
