name: Update Repository

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        default: 'latest'
  repository_dispatch:
    types: [kick]

jobs:
  generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo ${{ github.event.client_payload.version }}
      - name: Generate
        run: |
          ./gen.sh
        env:
          VERSION: ${{ inputs.version }}
      - name: Add HTML Update
        run: |
          git add index.html
          git config --global user.email "tools@mondoo.com"
          git config --global user.name "Mondoo Tools"
          git commit -m "Regenerated HTML"
          git push
      
